//
// Created by 孙璋亮 on 2019-08-28.
//

#ifndef COURIER_CLIENT_MACRO_DEFINITION_H
#define COURIER_CLIENT_MACRO_DEFINITION_H

//Marco part
#define SUCCESS 0
#define REGIST_SUCCESS 0
#define INVALID_USERNAME 1
#define INCORRECT_INFO 2
#define LENGTH_ERROR 1
#define LINK_ERROR 5


#endif //COURIER_CLIENT_MACRO_DEFINITION_H
